/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sep;

import javax.swing.JOptionPane;

/**
 *
 * @author JJ.NAVARRETE
 */
public class FrmAgregarNuevoUsuarioDesdeListaDocentes extends javax.swing.JFrame {

    
    /**
     * Creates new form FrmAgregarUsuario
     */
    public FrmAgregarNuevoUsuarioDesdeListaDocentes() {
        initComponents();
        
        jComboBoxTipoUsuario.setSelectedIndex(2);
        jComboBoxTipoUsuario.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosDocente = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDependencia = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelCurp = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldCurp = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDependencia = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jLabelContraseña = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jComboBoxTipoUsuario = new javax.swing.JComboBox();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Nuevo Usuario");

        jPanelDatosDocente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Docente"));
        jPanelDatosDocente.setMinimumSize(new java.awt.Dimension(284, 244));

        jLabelNombre.setText("Nombre:");

        jLabelDependencia.setText("Dependencia:");

        jLabelEmail.setText("Email:");

        jLabelCurp.setText("CURP:");

        jLabelTelefono.setText("Telefono:");

        jLabelUsuario.setText("Usuario:");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabelContraseña.setText("Contraseña:");

        javax.swing.GroupLayout jPanelDatosDocenteLayout = new javax.swing.GroupLayout(jPanelDatosDocente);
        jPanelDatosDocente.setLayout(jPanelDatosDocenteLayout);
        jPanelDatosDocenteLayout.setHorizontalGroup(
            jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosDocenteLayout.createSequentialGroup()
                .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosDocenteLayout.createSequentialGroup()
                        .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelContraseña)
                            .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosDocenteLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabelUsuario))
                                .addGroup(jPanelDatosDocenteLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelCurp)
                                            .addComponent(jLabelEmail)
                                            .addComponent(jLabelDependencia)
                                            .addComponent(jLabelNombre))
                                        .addComponent(jLabelTelefono, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCurp)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldDependencia)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldTelefono)
                            .addComponent(jTextFieldUsuario)
                            .addComponent(jPasswordFieldContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosDocenteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonAgregar)))
                .addGap(24, 24, 24))
        );
        jPanelDatosDocenteLayout.setVerticalGroup(
            jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosDocenteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurp)
                    .addComponent(jTextFieldCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDependencia)
                    .addComponent(jTextFieldDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContraseña)
                    .addComponent(jPasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtonAgregar))
        );

        jLabelTipoUsuario.setText("Tipo Usuario:");

        jComboBoxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione tipo usuario", "Administrador", "Docente" }));
        jComboBoxTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoUsuarioActionPerformed(evt);
            }
        });

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSEP.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatosDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelLogo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoUsuario)
                    .addComponent(jComboBoxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoUsuarioActionPerformed
        if (jComboBoxTipoUsuario.getSelectedItem().toString().equals("Seleccione tipo usuario")) {
            jTextFieldCurp.setEditable(false);
            jTextFieldDependencia.setEditable(false);
            jTextFieldEmail.setEditable(false);
            jTextFieldNombre.setEditable(false);
            jTextFieldTelefono.setEditable(false);
            jTextFieldUsuario.setEditable(false);
            jPasswordFieldContraseña.setEditable(false);

        }

        if (jComboBoxTipoUsuario.getSelectedItem().toString().equals("Administrador")) {
            jPanelDatosDocente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Administrador"));
            jTextFieldCurp.setText("");
            jTextFieldDependencia.setText("");
            jTextFieldEmail.setText("");
            jTextFieldNombre.setText("");
            jTextFieldTelefono.setText("");
            jTextFieldUsuario.setText("");
            jPasswordFieldContraseña.setText("");

            jLabelCurp.setVisible(false);
            jTextFieldCurp.setVisible(false);
            jLabelUsuario.setVisible(true);
            jTextFieldUsuario.setVisible(true);

            jTextFieldCurp.setEditable(true);
            jTextFieldDependencia.setEditable(true);
            jTextFieldEmail.setEditable(true);
            jTextFieldNombre.setEditable(true);
            jTextFieldTelefono.setEditable(true);
            jTextFieldUsuario.setEditable(true);
            jPasswordFieldContraseña.setEditable(true);

        }

        if (jComboBoxTipoUsuario.getSelectedItem().toString().equals("Docente")) {
            jPanelDatosDocente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Docente"));
            jTextFieldCurp.setText("");
            jTextFieldDependencia.setText("");
            jTextFieldEmail.setText("");
            jTextFieldNombre.setText("");
            jTextFieldTelefono.setText("");
            jTextFieldUsuario.setText("");
            jPasswordFieldContraseña.setText("");
            jLabelCurp.setVisible(true);
            jTextFieldCurp.setVisible(true);
            jLabelUsuario.setVisible(false);
            jTextFieldUsuario.setVisible(false);

            jTextFieldCurp.setEditable(true);
            jTextFieldDependencia.setEditable(true);
            jTextFieldEmail.setEditable(true);
            jTextFieldNombre.setEditable(true);
            jTextFieldTelefono.setEditable(true);
            jTextFieldUsuario.setEditable(true);
            jPasswordFieldContraseña.setEditable(true);

        }

    }//GEN-LAST:event_jComboBoxTipoUsuarioActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        validar();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void validar() {
        switch (jComboBoxTipoUsuario.getSelectedItem().toString()) {
            case "Administrador":
                String pass = String.valueOf(jPasswordFieldContraseña.getPassword());
                if (jTextFieldNombre.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere un nombre", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (jTextFieldDependencia.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere ingresar la dependencia.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (jTextFieldEmail.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere un e-mail.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (jTextFieldTelefono.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere un telefono", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (jTextFieldUsuario.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Ingrese un Usuario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (pass.equals("")) {
                    JOptionPane.showMessageDialog(this, "Ingrese un Usuario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {
                    registrarAdministrador();
                }
                break;

            case "Docente":
                String pw = String.valueOf(jPasswordFieldContraseña.getPassword());
                if (jTextFieldCurp.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere la CURP", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (jTextFieldNombre.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere un nombre", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (jTextFieldDependencia.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere ingresar la dependencia.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (jTextFieldEmail.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere un e-mail.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (jTextFieldTelefono.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Se requiere un telefono", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (pw.equals("")) {
                    JOptionPane.showMessageDialog(this, "Ingrese un Usuario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {
                    registrarDocente();
                }
                break;

        }

    }

    private void registrarAdministrador() {

        String nombre = jTextFieldNombre.getText();
        String dependencia = jTextFieldDependencia.getText();
        String email = jTextFieldEmail.getText();
        String telefono = jTextFieldTelefono.getText();
        String usuario = jTextFieldUsuario.getText();
        String contraseña = String.valueOf(jPasswordFieldContraseña.getPassword());

        String[] datos = {nombre, dependencia, email, telefono, usuario, contraseña};
        BD bd = new BD();
        String consulta = bd.registrarAdministrador(datos);
        if (consulta.equals("Ok")) {
            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            FrmListaDocentes.instancia.cargarTabla();
            
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar usuario.", "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void registrarDocente() {
        String curp = jTextFieldCurp.getText();
        String nombre = jTextFieldNombre.getText();
        String dependencia = jTextFieldDependencia.getText();
        String email = jTextFieldEmail.getText();
        String telefono = jTextFieldTelefono.getText();
        String contraseña = String.valueOf(jPasswordFieldContraseña.getPassword());

        String[] datos = {curp, nombre, dependencia, email, telefono, contraseña};
        BD bd = new BD();
        String consulta = bd.registrarDocente(datos);

        if (consulta.equals("Ok")) {
            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            FrmListaDocentes.instancia.cargarTabla();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar usuario.", "Advertencia", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarNuevoUsuarioDesdeListaDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarNuevoUsuarioDesdeListaDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarNuevoUsuarioDesdeListaDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarNuevoUsuarioDesdeListaDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarNuevoUsuarioDesdeListaDocentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JComboBox jComboBoxTipoUsuario;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCurp;
    private javax.swing.JLabel jLabelDependencia;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelDatosDocente;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldCurp;
    private javax.swing.JTextField jTextFieldDependencia;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
