/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sep;

/**
 *
 * @author JJ.NAVARRETE
 */
public class FrmBusquedaDocente extends javax.swing.JFrame {

    String curp = "";

    /**
     * Creates new form FrmDocente
     */
    public FrmBusquedaDocente(String curp) {
        initComponents();
        this.curp = curp;
        datosDocente(this.curp);

    }

    private void datosDocente(String curp) {
        String CURP = curp;
        BD bd = new BD();
        String[] datos = bd.obtenerDatosDocente(CURP);
        String nombre1 = datos[3];
        String nombre2 = datos[4];
        String apellidop = datos[1];
        String apellidom = datos[2];

        try {
            String nombreCompleto = nombre1.concat(" ").concat(nombre2).concat(" ").concat(apellidop).concat(" ").concat(apellidom);
            jLabelNombreDocente.setText(nombreCompleto);
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreDocente = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonDatosPersonales = new javax.swing.JButton();
        jLabelDatosPersonales = new javax.swing.JLabel();
        jButtonPlantelAdscripcion = new javax.swing.JButton();
        jLabelPlantelAdscripcion = new javax.swing.JLabel();
        jButtonAsignaturas = new javax.swing.JButton();
        jLabelAsignaturas = new javax.swing.JLabel();
        jButtonDiplomado = new javax.swing.JButton();
        jLabelDiplomado = new javax.swing.JLabel();
        jLabelEstudiosRealizados = new javax.swing.JLabel();
        jButtonEstudiosRealizados = new javax.swing.JButton();
        jButtonIdiomas = new javax.swing.JButton();
        Idiomas = new javax.swing.JLabel();
        jButtonOtraInstitucionLaboral = new javax.swing.JButton();
        jLabelOtraInstitucionLaboral = new javax.swing.JLabel();
        jButtonExperienciaLaboral = new javax.swing.JButton();
        jLabelExperienciaLaboral = new javax.swing.JLabel();
        jButtonComentarios = new javax.swing.JButton();
        jLabelComentarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas Docentes");

        jLabelNombreDocente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNombreDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreDocente.setText("Nombre Docente");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSEP.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Menú"));

        jButtonDatosPersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos personales.png"))); // NOI18N
        jButtonDatosPersonales.setToolTipText("Modificar");
        jButtonDatosPersonales.setBorderPainted(false);
        jButtonDatosPersonales.setContentAreaFilled(false);
        jButtonDatosPersonales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDatosPersonales.setFocusPainted(false);
        jButtonDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosPersonalesActionPerformed(evt);
            }
        });

        jLabelDatosPersonales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatosPersonales.setText("Datos Pesonales");

        jButtonPlantelAdscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plantel de adscripcion.png"))); // NOI18N
        jButtonPlantelAdscripcion.setToolTipText("Modificar");
        jButtonPlantelAdscripcion.setBorderPainted(false);
        jButtonPlantelAdscripcion.setContentAreaFilled(false);
        jButtonPlantelAdscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlantelAdscripcion.setFocusPainted(false);
        jButtonPlantelAdscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlantelAdscripcionActionPerformed(evt);
            }
        });

        jLabelPlantelAdscripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlantelAdscripcion.setText("Plantel Adscripción");

        jButtonAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asignaturas.png"))); // NOI18N
        jButtonAsignaturas.setToolTipText("Modificar");
        jButtonAsignaturas.setBorderPainted(false);
        jButtonAsignaturas.setContentAreaFilled(false);
        jButtonAsignaturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAsignaturas.setFocusPainted(false);
        jButtonAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignaturasActionPerformed(evt);
            }
        });

        jLabelAsignaturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAsignaturas.setText("Asignatura por Semestre");

        jButtonDiplomado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diplomado.png"))); // NOI18N
        jButtonDiplomado.setToolTipText("Modificar");
        jButtonDiplomado.setBorderPainted(false);
        jButtonDiplomado.setContentAreaFilled(false);
        jButtonDiplomado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDiplomado.setFocusPainted(false);
        jButtonDiplomado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiplomadoActionPerformed(evt);
            }
        });

        jLabelDiplomado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiplomado.setText("Diplomado Proformdems");

        jLabelEstudiosRealizados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstudiosRealizados.setText("Estudios Realizados");

        jButtonEstudiosRealizados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudios_realizados.png"))); // NOI18N
        jButtonEstudiosRealizados.setToolTipText("Modificar");
        jButtonEstudiosRealizados.setBorderPainted(false);
        jButtonEstudiosRealizados.setContentAreaFilled(false);
        jButtonEstudiosRealizados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEstudiosRealizados.setFocusPainted(false);
        jButtonEstudiosRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstudiosRealizadosActionPerformed(evt);
            }
        });

        jButtonIdiomas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/idiomas.png"))); // NOI18N
        jButtonIdiomas.setToolTipText("Modificar");
        jButtonIdiomas.setBorderPainted(false);
        jButtonIdiomas.setContentAreaFilled(false);
        jButtonIdiomas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIdiomas.setFocusPainted(false);
        jButtonIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdiomasActionPerformed(evt);
            }
        });

        Idiomas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Idiomas.setText("Idiomas");

        jButtonOtraInstitucionLaboral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/otra.png"))); // NOI18N
        jButtonOtraInstitucionLaboral.setToolTipText("Modificar");
        jButtonOtraInstitucionLaboral.setBorderPainted(false);
        jButtonOtraInstitucionLaboral.setContentAreaFilled(false);
        jButtonOtraInstitucionLaboral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOtraInstitucionLaboral.setFocusPainted(false);
        jButtonOtraInstitucionLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtraInstitucionLaboralActionPerformed(evt);
            }
        });

        jLabelOtraInstitucionLaboral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOtraInstitucionLaboral.setText("Otra Institución Laboral");

        jButtonExperienciaLaboral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/experiencia laboral.png"))); // NOI18N
        jButtonExperienciaLaboral.setToolTipText("Modificar");
        jButtonExperienciaLaboral.setBorderPainted(false);
        jButtonExperienciaLaboral.setContentAreaFilled(false);
        jButtonExperienciaLaboral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExperienciaLaboral.setFocusPainted(false);
        jButtonExperienciaLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExperienciaLaboralActionPerformed(evt);
            }
        });

        jLabelExperienciaLaboral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExperienciaLaboral.setText("Experiencia Laboral");

        jButtonComentarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comentario.png"))); // NOI18N
        jButtonComentarios.setToolTipText("Modificar");
        jButtonComentarios.setBorderPainted(false);
        jButtonComentarios.setContentAreaFilled(false);
        jButtonComentarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonComentarios.setFocusPainted(false);
        jButtonComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComentariosActionPerformed(evt);
            }
        });

        jLabelComentarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelComentarios.setText("Comentarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPlantelAdscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPlantelAdscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAsignaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDiplomado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDiplomado, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelEstudiosRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEstudiosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonIdiomas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Idiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOtraInstitucionLaboral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOtraInstitucionLaboral, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExperienciaLaboral)
                            .addComponent(jLabelExperienciaLaboral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonComentarios)
                            .addComponent(jLabelComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonEstudiosRealizados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEstudiosRealizados))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonDiplomado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelDiplomado))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonAsignaturas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelAsignaturas))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonPlantelAdscripcion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelPlantelAdscripcion))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonDatosPersonales)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelDatosPersonales))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOtraInstitucionLaboral)
                            .addComponent(Idiomas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonIdiomas)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButtonOtraInstitucionLaboral)
                                    .addGap(20, 20, 20)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonExperienciaLaboral)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButtonComentarios)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelComentarios)
                                        .addComponent(jLabelExperienciaLaboral)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabelLogo))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosPersonalesActionPerformed
        FrmDatosPersonales datos = new FrmDatosPersonales(this.curp);
        datos.setLocationRelativeTo(null);
        datos.setVisible(true);
    }//GEN-LAST:event_jButtonDatosPersonalesActionPerformed

    private void jButtonPlantelAdscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlantelAdscripcionActionPerformed
        FrmPlantel plantel = new FrmPlantel(curp);
        plantel.setLocationRelativeTo(null);
        plantel.setVisible(true);
    }//GEN-LAST:event_jButtonPlantelAdscripcionActionPerformed

    private void jButtonAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignaturasActionPerformed
        FrmAsignatura asignaturas = new FrmAsignatura(curp);
        asignaturas.setLocationRelativeTo(null);
        asignaturas.setVisible(true);
    }//GEN-LAST:event_jButtonAsignaturasActionPerformed

    private void jButtonDiplomadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiplomadoActionPerformed
        FrmDiplomado diplomado = new FrmDiplomado(curp);
        diplomado.setLocationRelativeTo(null);
        diplomado.setVisible(true);
    }//GEN-LAST:event_jButtonDiplomadoActionPerformed

    private void jButtonEstudiosRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstudiosRealizadosActionPerformed
        FrmEstudiosRealizados estudiosRealizados = new FrmEstudiosRealizados(curp);
        estudiosRealizados.setLocationRelativeTo(null);
        estudiosRealizados.setVisible(true);
    }//GEN-LAST:event_jButtonEstudiosRealizadosActionPerformed

    private void jButtonIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdiomasActionPerformed
        FrmIdiomas idiomas = new FrmIdiomas(curp);
        idiomas.setLocationRelativeTo(null);
        idiomas.setVisible(true);
    }//GEN-LAST:event_jButtonIdiomasActionPerformed

    private void jButtonOtraInstitucionLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtraInstitucionLaboralActionPerformed
        FrmOtraInstitucion otraInstitucion = new FrmOtraInstitucion(curp);
        otraInstitucion.setLocationRelativeTo(null);
        otraInstitucion.setVisible(true);
    }//GEN-LAST:event_jButtonOtraInstitucionLaboralActionPerformed

    private void jButtonExperienciaLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExperienciaLaboralActionPerformed
        FrmExperienciaLaboral experiencia = new FrmExperienciaLaboral(curp);
        experiencia.setLocationRelativeTo(null);
        experiencia.setVisible(true);
    }//GEN-LAST:event_jButtonExperienciaLaboralActionPerformed

    private void jButtonComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComentariosActionPerformed
        FrmComentariosConsultasDocentes comentarios = new FrmComentariosConsultasDocentes(curp);
        comentarios.setLocationRelativeTo(null);
        comentarios.setVisible(true);
    }//GEN-LAST:event_jButtonComentariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBusquedaDocente("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Idiomas;
    private javax.swing.JButton jButtonAsignaturas;
    private javax.swing.JButton jButtonComentarios;
    private javax.swing.JButton jButtonDatosPersonales;
    private javax.swing.JButton jButtonDiplomado;
    private javax.swing.JButton jButtonEstudiosRealizados;
    private javax.swing.JButton jButtonExperienciaLaboral;
    private javax.swing.JButton jButtonIdiomas;
    private javax.swing.JButton jButtonOtraInstitucionLaboral;
    private javax.swing.JButton jButtonPlantelAdscripcion;
    private javax.swing.JLabel jLabelAsignaturas;
    private javax.swing.JLabel jLabelComentarios;
    private javax.swing.JLabel jLabelDatosPersonales;
    private javax.swing.JLabel jLabelDiplomado;
    private javax.swing.JLabel jLabelEstudiosRealizados;
    private javax.swing.JLabel jLabelExperienciaLaboral;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreDocente;
    private javax.swing.JLabel jLabelOtraInstitucionLaboral;
    private javax.swing.JLabel jLabelPlantelAdscripcion;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
