/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sep;

/**
 *
 * @author GermyMc
 */
public class FrmIdiomas extends javax.swing.JFrame {

    String curp = "";
    String lenguaMaterna = "";

    String idioma1 = "";
    String lecturaIdioma1 = "";
    String escrituraIdioma1 = "";
    String habladoIdioma1 = "";

    String idioma2 = "";
    String lecturaIdioma2 = "";
    String escrituraIdioma2 = "";
    String habladoIdioma2 = "";

    /**
     * Creates new form FrmIdiomas
     */
    public FrmIdiomas(String curp) {
        this.curp = curp;
        initComponents();
        obtenerDatosIdiomas();
        deshabilitarElementos();
    }

    private synchronized void obtenerDatosIdiomas() {
        BD bd = new BD();
        String[] datosIdiomas = bd.obtenerDatosIdiomas(curp);

        lenguaMaterna = datosIdiomas[0];

        idioma1 = datosIdiomas[1];
        lecturaIdioma1 = datosIdiomas[2];
        escrituraIdioma1 = datosIdiomas[3];
        habladoIdioma1 = datosIdiomas[4];

        idioma2 = datosIdiomas[5];
        lecturaIdioma2 = datosIdiomas[6];
        escrituraIdioma2 = datosIdiomas[7];
        habladoIdioma2 = datosIdiomas[8];

        jTextFieldLenguaMaterna.setText(lenguaMaterna);
        jTextFieldIdioma1.setText(idioma1);
        jTextFieldIdioma2.setText(idioma2);
        jTextFieldEscrituraIdioma1.setText(escrituraIdioma1);
        jTextFieldEscrituraIdioma2.setText(escrituraIdioma2);
        jTextFieldLecturaIdioma1.setText(lecturaIdioma1);
        jTextFieldLecturaIdioma2.setText(lecturaIdioma2);
        jTextFieldHabladoIdioma1.setText(habladoIdioma1);
        jTextFieldHabladoIdioma2.setText(habladoIdioma2);

    }

    private void deshabilitarElementos() {
        jTextFieldLenguaMaterna.setEditable(false);
        jTextFieldIdioma1.setEditable(false);
        jTextFieldIdioma2.setEditable(false);
        jTextFieldEscrituraIdioma1.setEditable(false);
        jTextFieldEscrituraIdioma2.setEditable(false);
        jTextFieldLecturaIdioma1.setEditable(false);
        jTextFieldLecturaIdioma2.setEditable(false);
        jTextFieldHabladoIdioma1.setEditable(false);
        jTextFieldHabladoIdioma2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLenguaMaterna = new javax.swing.JLabel();
        jTextFieldLenguaMaterna = new javax.swing.JTextField();
        jPanelIdioma1 = new javax.swing.JPanel();
        jLabelIdioma1 = new javax.swing.JLabel();
        jLabelLecturaIdioma1 = new javax.swing.JLabel();
        jLabelEscrituraIdioma1 = new javax.swing.JLabel();
        jLabelHabladoIdioma1 = new javax.swing.JLabel();
        jTextFieldIdioma1 = new javax.swing.JTextField();
        jTextFieldLecturaIdioma1 = new javax.swing.JTextField();
        jTextFieldEscrituraIdioma1 = new javax.swing.JTextField();
        jTextFieldHabladoIdioma1 = new javax.swing.JTextField();
        jPanelIdioma2 = new javax.swing.JPanel();
        jLabelIdioma2 = new javax.swing.JLabel();
        jLabelLecturaIdioma2 = new javax.swing.JLabel();
        jLabelEscrituraIdioma2 = new javax.swing.JLabel();
        jLabelHabladoIdioma2 = new javax.swing.JLabel();
        jTextFieldIdioma2 = new javax.swing.JTextField();
        jTextFieldLecturaIdioma2 = new javax.swing.JTextField();
        jTextFieldHabladoIdioma2 = new javax.swing.JTextField();
        jTextFieldEscrituraIdioma2 = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Idiomas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Idiomas"));

        jLabelLenguaMaterna.setText("Lengua Materna:");

        jTextFieldLenguaMaterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLenguaMaternaActionPerformed(evt);
            }
        });

        jPanelIdioma1.setBorder(javax.swing.BorderFactory.createTitledBorder("Idioma 1"));

        jLabelIdioma1.setText("Idioma 1:");

        jLabelLecturaIdioma1.setText("Lectura (%):");

        jLabelEscrituraIdioma1.setText("Escritura (%):");

        jLabelHabladoIdioma1.setText("Hablado (%):");

        javax.swing.GroupLayout jPanelIdioma1Layout = new javax.swing.GroupLayout(jPanelIdioma1);
        jPanelIdioma1.setLayout(jPanelIdioma1Layout);
        jPanelIdioma1Layout.setHorizontalGroup(
            jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdioma1Layout.createSequentialGroup()
                .addGroup(jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIdioma1)
                    .addComponent(jLabelLecturaIdioma1)
                    .addComponent(jLabelEscrituraIdioma1)
                    .addComponent(jLabelHabladoIdioma1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIdioma1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldHabladoIdioma1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(jTextFieldEscrituraIdioma1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldLecturaIdioma1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanelIdioma1Layout.setVerticalGroup(
            jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIdioma1Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdioma1)
                    .addComponent(jTextFieldIdioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLecturaIdioma1)
                    .addComponent(jTextFieldLecturaIdioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEscrituraIdioma1)
                    .addComponent(jTextFieldEscrituraIdioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdioma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHabladoIdioma1)
                    .addComponent(jTextFieldHabladoIdioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelIdioma2.setBorder(javax.swing.BorderFactory.createTitledBorder("Idioma 2"));

        jLabelIdioma2.setText("Idioma 2:");

        jLabelLecturaIdioma2.setText("Lectura (%):");

        jLabelEscrituraIdioma2.setText("Escritura (%):");

        jLabelHabladoIdioma2.setText("Hablado (%):");

        javax.swing.GroupLayout jPanelIdioma2Layout = new javax.swing.GroupLayout(jPanelIdioma2);
        jPanelIdioma2.setLayout(jPanelIdioma2Layout);
        jPanelIdioma2Layout.setHorizontalGroup(
            jPanelIdioma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdioma2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelIdioma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLecturaIdioma2)
                    .addComponent(jLabelIdioma2)
                    .addComponent(jLabelEscrituraIdioma2)
                    .addComponent(jLabelHabladoIdioma2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdioma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLecturaIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabladoIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEscrituraIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIdioma2Layout.setVerticalGroup(
            jPanelIdioma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIdioma2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelIdioma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdioma2)
                    .addComponent(jTextFieldIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdioma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLecturaIdioma2)
                    .addComponent(jTextFieldLecturaIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdioma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEscrituraIdioma2)
                    .addComponent(jTextFieldEscrituraIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelIdioma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHabladoIdioma2)
                    .addComponent(jTextFieldHabladoIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIdioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelIdioma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLenguaMaterna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLenguaMaterna, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLenguaMaterna)
                    .addComponent(jTextFieldLenguaMaterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelIdioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelIdioma2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSEP.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabelLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLenguaMaternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLenguaMaternaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLenguaMaternaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIdiomas("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEscrituraIdioma1;
    private javax.swing.JLabel jLabelEscrituraIdioma2;
    private javax.swing.JLabel jLabelHabladoIdioma1;
    private javax.swing.JLabel jLabelHabladoIdioma2;
    private javax.swing.JLabel jLabelIdioma1;
    private javax.swing.JLabel jLabelIdioma2;
    private javax.swing.JLabel jLabelLecturaIdioma1;
    private javax.swing.JLabel jLabelLecturaIdioma2;
    private javax.swing.JLabel jLabelLenguaMaterna;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelIdioma1;
    private javax.swing.JPanel jPanelIdioma2;
    private javax.swing.JTextField jTextFieldEscrituraIdioma1;
    private javax.swing.JTextField jTextFieldEscrituraIdioma2;
    private javax.swing.JTextField jTextFieldHabladoIdioma1;
    private javax.swing.JTextField jTextFieldHabladoIdioma2;
    private javax.swing.JTextField jTextFieldIdioma1;
    private javax.swing.JTextField jTextFieldIdioma2;
    private javax.swing.JTextField jTextFieldLecturaIdioma1;
    private javax.swing.JTextField jTextFieldLecturaIdioma2;
    private javax.swing.JTextField jTextFieldLenguaMaterna;
    // End of variables declaration//GEN-END:variables
}
